/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedClientOnlyRouteImport } from './routes/_authed/client-only'
import { Route as AuthedDataOnlyRouteImport } from './routes/_authed/data-only'
import { Route as AuthedItemsRouteImport } from './routes/_authed/items'
import { Route as AuthedStreamRouteImport } from './routes/_authed/stream'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedClientOnlyRoute = AuthedClientOnlyRouteImport.update({
  id: '/client-only',
  path: '/client-only',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDataOnlyRoute = AuthedDataOnlyRouteImport.update({
  id: '/data-only',
  path: '/data-only',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedItemsRoute = AuthedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStreamRoute = AuthedStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/client-only': typeof AuthedClientOnlyRoute
  '/data-only': typeof AuthedDataOnlyRoute
  '/items': typeof AuthedItemsRoute
  '/stream': typeof AuthedStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/client-only': typeof AuthedClientOnlyRoute
  '/data-only': typeof AuthedDataOnlyRoute
  '/items': typeof AuthedItemsRoute
  '/stream': typeof AuthedStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/client-only': typeof AuthedClientOnlyRoute
  '/_authed/data-only': typeof AuthedDataOnlyRoute
  '/_authed/items': typeof AuthedItemsRoute
  '/_authed/stream': typeof AuthedStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/client-only'
    | '/data-only'
    | '/items'
    | '/stream'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/client-only'
    | '/data-only'
    | '/items'
    | '/stream'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/client-only'
    | '/_authed/data-only'
    | '/_authed/items'
    | '/_authed/stream'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/client-only': {
      id: '/_authed/client-only'
      path: '/client-only'
      fullPath: '/client-only'
      preLoaderRoute: typeof AuthedClientOnlyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/data-only': {
      id: '/_authed/data-only'
      path: '/data-only'
      fullPath: '/data-only'
      preLoaderRoute: typeof AuthedDataOnlyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/items': {
      id: '/_authed/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthedItemsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stream': {
      id: '/_authed/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof AuthedStreamRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedClientOnlyRoute: typeof AuthedClientOnlyRoute
  AuthedDataOnlyRoute: typeof AuthedDataOnlyRoute
  AuthedItemsRoute: typeof AuthedItemsRoute
  AuthedStreamRoute: typeof AuthedStreamRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedClientOnlyRoute: AuthedClientOnlyRoute,
  AuthedDataOnlyRoute: AuthedDataOnlyRoute,
  AuthedItemsRoute: AuthedItemsRoute,
  AuthedStreamRoute: AuthedStreamRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
