/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedSecurityRouteImport } from './routes/_authed/security'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as ApiImagesRouteImport } from './routes/api/images'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as FeedSlugRouteImport } from './routes/feed/$slug'
import { Route as ImagesFileRouteImport } from './routes/images/$file'
import { Route as AuthedPodcastsSlugRouteImport } from './routes/_authed/podcasts/$slug'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSettingsSecurityRouteImport } from './routes/_authed/settings/security'
import { Route as AdminQueuesSplatRouteImport } from './routes/admin/queues/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEpisodesIdAudioRouteImport } from './routes/api/episodes/$id/audio'
import { Route as AuthedPodcastsSlugEpisodesEpisodeSlugRouteImport } from './routes/_authed/podcasts/$slug_.episodes.$episodeSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSecurityRoute = AuthedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiImagesRoute = ApiImagesRouteImport.update({
  id: '/api/images',
  path: '/api/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugRoute = FeedSlugRouteImport.update({
  id: '/feed/$slug',
  path: '/feed/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesFileRoute = ImagesFileRouteImport.update({
  id: '/images/$file',
  path: '/images/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPodcastsSlugRoute = AuthedPodcastsSlugRouteImport.update({
  id: '/podcasts/$slug',
  path: '/podcasts/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsSecurityRoute = AuthedSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AdminQueuesSplatRoute = AdminQueuesSplatRouteImport.update({
  id: '/admin/queues/$',
  path: '/admin/queues/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEpisodesIdAudioRoute = ApiEpisodesIdAudioRouteImport.update({
  id: '/api/episodes/$id/audio',
  path: '/api/episodes/$id/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPodcastsSlugEpisodesEpisodeSlugRoute =
  AuthedPodcastsSlugEpisodesEpisodeSlugRouteImport.update({
    id: '/podcasts/$slug_/episodes/$episodeSlug',
    path: '/podcasts/$slug/episodes/$episodeSlug',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/security': typeof AuthedSecurityRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/api/images': typeof ApiImagesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/images/$file': typeof ImagesFileRoute
  '/podcasts/$slug': typeof AuthedPodcastsSlugRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/admin/queues/$': typeof AdminQueuesSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/api/episodes/$id/audio': typeof ApiEpisodesIdAudioRoute
  '/podcasts/$slug/episodes/$episodeSlug': typeof AuthedPodcastsSlugEpisodesEpisodeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/security': typeof AuthedSecurityRoute
  '/api/images': typeof ApiImagesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/images/$file': typeof ImagesFileRoute
  '/podcasts/$slug': typeof AuthedPodcastsSlugRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/admin/queues/$': typeof AdminQueuesSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/api/episodes/$id/audio': typeof ApiEpisodesIdAudioRoute
  '/podcasts/$slug/episodes/$episodeSlug': typeof AuthedPodcastsSlugEpisodesEpisodeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/security': typeof AuthedSecurityRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/api/images': typeof ApiImagesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/images/$file': typeof ImagesFileRoute
  '/_authed/podcasts/$slug': typeof AuthedPodcastsSlugRoute
  '/_authed/settings/security': typeof AuthedSettingsSecurityRoute
  '/admin/queues/$': typeof AdminQueuesSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/api/episodes/$id/audio': typeof ApiEpisodesIdAudioRoute
  '/_authed/podcasts/$slug_/episodes/$episodeSlug': typeof AuthedPodcastsSlugEpisodesEpisodeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/security'
    | '/settings'
    | '/api/images'
    | '/api/uploads'
    | '/feed/$slug'
    | '/images/$file'
    | '/podcasts/$slug'
    | '/settings/security'
    | '/admin/queues/$'
    | '/api/auth/$'
    | '/settings/'
    | '/api/episodes/$id/audio'
    | '/podcasts/$slug/episodes/$episodeSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/security'
    | '/api/images'
    | '/api/uploads'
    | '/feed/$slug'
    | '/images/$file'
    | '/podcasts/$slug'
    | '/settings/security'
    | '/admin/queues/$'
    | '/api/auth/$'
    | '/settings'
    | '/api/episodes/$id/audio'
    | '/podcasts/$slug/episodes/$episodeSlug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/security'
    | '/_authed/settings'
    | '/api/images'
    | '/api/uploads'
    | '/feed/$slug'
    | '/images/$file'
    | '/_authed/podcasts/$slug'
    | '/_authed/settings/security'
    | '/admin/queues/$'
    | '/api/auth/$'
    | '/_authed/settings/'
    | '/api/episodes/$id/audio'
    | '/_authed/podcasts/$slug_/episodes/$episodeSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiImagesRoute: typeof ApiImagesRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  FeedSlugRoute: typeof FeedSlugRoute
  ImagesFileRoute: typeof ImagesFileRoute
  AdminQueuesSplatRoute: typeof AdminQueuesSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEpisodesIdAudioRoute: typeof ApiEpisodesIdAudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/security': {
      id: '/_authed/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthedSecurityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/images': {
      id: '/api/images'
      path: '/api/images'
      fullPath: '/api/images'
      preLoaderRoute: typeof ApiImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug': {
      id: '/feed/$slug'
      path: '/feed/$slug'
      fullPath: '/feed/$slug'
      preLoaderRoute: typeof FeedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$file': {
      id: '/images/$file'
      path: '/images/$file'
      fullPath: '/images/$file'
      preLoaderRoute: typeof ImagesFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/podcasts/$slug': {
      id: '/_authed/podcasts/$slug'
      path: '/podcasts/$slug'
      fullPath: '/podcasts/$slug'
      preLoaderRoute: typeof AuthedPodcastsSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsSecurityRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/admin/queues/$': {
      id: '/admin/queues/$'
      path: '/admin/queues/$'
      fullPath: '/admin/queues/$'
      preLoaderRoute: typeof AdminQueuesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/episodes/$id/audio': {
      id: '/api/episodes/$id/audio'
      path: '/api/episodes/$id/audio'
      fullPath: '/api/episodes/$id/audio'
      preLoaderRoute: typeof ApiEpisodesIdAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/podcasts/$slug_/episodes/$episodeSlug': {
      id: '/_authed/podcasts/$slug_/episodes/$episodeSlug'
      path: '/podcasts/$slug/episodes/$episodeSlug'
      fullPath: '/podcasts/$slug/episodes/$episodeSlug'
      preLoaderRoute: typeof AuthedPodcastsSlugEpisodesEpisodeSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsSecurityRoute: typeof AuthedSettingsSecurityRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsSecurityRoute: AuthedSettingsSecurityRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedSecurityRoute: typeof AuthedSecurityRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedPodcastsSlugRoute: typeof AuthedPodcastsSlugRoute
  AuthedPodcastsSlugEpisodesEpisodeSlugRoute: typeof AuthedPodcastsSlugEpisodesEpisodeSlugRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSecurityRoute: AuthedSecurityRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedPodcastsSlugRoute: AuthedPodcastsSlugRoute,
  AuthedPodcastsSlugEpisodesEpisodeSlugRoute:
    AuthedPodcastsSlugEpisodesEpisodeSlugRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiImagesRoute: ApiImagesRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  FeedSlugRoute: FeedSlugRoute,
  ImagesFileRoute: ImagesFileRoute,
  AdminQueuesSplatRoute: AdminQueuesSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEpisodesIdAudioRoute: ApiEpisodesIdAudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
