/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TosRouteImport } from './routes/tos'
import { Route as AuthedSecurityRouteImport } from './routes/_authed/security'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as ApiImagesRouteImport } from './routes/api/images'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as FeedSlugRouteImport } from './routes/feed/$slug'
import { Route as ImagesFileRouteImport } from './routes/images/$file'
import { Route as PodcastsSlugRouteImport } from './routes/podcasts/$slug'
import { Route as SShortSlugRouteImport } from './routes/s/$shortSlug'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSettingsSecurityRouteImport } from './routes/_authed/settings/security'
import { Route as AdminQueuesSplatRouteImport } from './routes/admin/queues/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as EmbedSlugEpisodeSlugRouteImport } from './routes/embed/$slug.$episodeSlug'
import { Route as ListenSlugEpisodeSlugRouteImport } from './routes/listen/$slug.$episodeSlug'
import { Route as AuthedPodcastsSlugManageRouteImport } from './routes/_authed/podcasts/$slug.manage'
import { Route as ApiEpisodesIdActivityRouteImport } from './routes/api/episodes/$id/activity'
import { Route as ApiEpisodesIdAudioRouteImport } from './routes/api/episodes/$id/audio'
import { Route as ApiPodcastsSlugEventsRouteImport } from './routes/api/podcasts/$slug/events'
import { Route as PodcastsSlugEpisodesEpisodeSlugRouteImport } from './routes/podcasts/$slug_.episodes.$episodeSlug'
import { Route as AuthedPodcastsSlugEpisodesEpisodeSlugManageRouteImport } from './routes/_authed/podcasts/$slug_.episodes.$episodeSlug.manage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSecurityRoute = AuthedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiImagesRoute = ApiImagesRouteImport.update({
  id: '/api/images',
  path: '/api/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugRoute = FeedSlugRouteImport.update({
  id: '/feed/$slug',
  path: '/feed/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesFileRoute = ImagesFileRouteImport.update({
  id: '/images/$file',
  path: '/images/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsSlugRoute = PodcastsSlugRouteImport.update({
  id: '/podcasts/$slug',
  path: '/podcasts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SShortSlugRoute = SShortSlugRouteImport.update({
  id: '/s/$shortSlug',
  path: '/s/$shortSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsSecurityRoute = AuthedSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AdminQueuesSplatRoute = AdminQueuesSplatRouteImport.update({
  id: '/admin/queues/$',
  path: '/admin/queues/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedSlugEpisodeSlugRoute = EmbedSlugEpisodeSlugRouteImport.update({
  id: '/embed/$slug/$episodeSlug',
  path: '/embed/$slug/$episodeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenSlugEpisodeSlugRoute = ListenSlugEpisodeSlugRouteImport.update({
  id: '/listen/$slug/$episodeSlug',
  path: '/listen/$slug/$episodeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPodcastsSlugManageRoute =
  AuthedPodcastsSlugManageRouteImport.update({
    id: '/podcasts/$slug/manage',
    path: '/podcasts/$slug/manage',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiEpisodesIdActivityRoute = ApiEpisodesIdActivityRouteImport.update({
  id: '/api/episodes/$id/activity',
  path: '/api/episodes/$id/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEpisodesIdAudioRoute = ApiEpisodesIdAudioRouteImport.update({
  id: '/api/episodes/$id/audio',
  path: '/api/episodes/$id/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPodcastsSlugEventsRoute = ApiPodcastsSlugEventsRouteImport.update({
  id: '/api/podcasts/$slug/events',
  path: '/api/podcasts/$slug/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsSlugEpisodesEpisodeSlugRoute =
  PodcastsSlugEpisodesEpisodeSlugRouteImport.update({
    id: '/podcasts/$slug_/episodes/$episodeSlug',
    path: '/podcasts/$slug/episodes/$episodeSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedPodcastsSlugEpisodesEpisodeSlugManageRoute =
  AuthedPodcastsSlugEpisodesEpisodeSlugManageRouteImport.update({
    id: '/podcasts/$slug_/episodes/$episodeSlug/manage',
    path: '/podcasts/$slug/episodes/$episodeSlug/manage',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/security': typeof AuthedSecurityRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/api/images': typeof ApiImagesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/images/$file': typeof ImagesFileRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/s/$shortSlug': typeof SShortSlugRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/admin/queues/$': typeof AdminQueuesSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/embed/$slug/$episodeSlug': typeof EmbedSlugEpisodeSlugRoute
  '/listen/$slug/$episodeSlug': typeof ListenSlugEpisodeSlugRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/podcasts/$slug/manage': typeof AuthedPodcastsSlugManageRoute
  '/api/episodes/$id/activity': typeof ApiEpisodesIdActivityRoute
  '/api/episodes/$id/audio': typeof ApiEpisodesIdAudioRoute
  '/api/podcasts/$slug/events': typeof ApiPodcastsSlugEventsRoute
  '/podcasts/$slug/episodes/$episodeSlug': typeof PodcastsSlugEpisodesEpisodeSlugRoute
  '/podcasts/$slug/episodes/$episodeSlug/manage': typeof AuthedPodcastsSlugEpisodesEpisodeSlugManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/security': typeof AuthedSecurityRoute
  '/api/images': typeof ApiImagesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/images/$file': typeof ImagesFileRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/s/$shortSlug': typeof SShortSlugRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/admin/queues/$': typeof AdminQueuesSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/embed/$slug/$episodeSlug': typeof EmbedSlugEpisodeSlugRoute
  '/listen/$slug/$episodeSlug': typeof ListenSlugEpisodeSlugRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/podcasts/$slug/manage': typeof AuthedPodcastsSlugManageRoute
  '/api/episodes/$id/activity': typeof ApiEpisodesIdActivityRoute
  '/api/episodes/$id/audio': typeof ApiEpisodesIdAudioRoute
  '/api/podcasts/$slug/events': typeof ApiPodcastsSlugEventsRoute
  '/podcasts/$slug/episodes/$episodeSlug': typeof PodcastsSlugEpisodesEpisodeSlugRoute
  '/podcasts/$slug/episodes/$episodeSlug/manage': typeof AuthedPodcastsSlugEpisodesEpisodeSlugManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/tos': typeof TosRoute
  '/_authed/security': typeof AuthedSecurityRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/api/images': typeof ApiImagesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/feed/$slug': typeof FeedSlugRoute
  '/images/$file': typeof ImagesFileRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/s/$shortSlug': typeof SShortSlugRoute
  '/_authed/settings/security': typeof AuthedSettingsSecurityRoute
  '/admin/queues/$': typeof AdminQueuesSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/embed/$slug/$episodeSlug': typeof EmbedSlugEpisodeSlugRoute
  '/listen/$slug/$episodeSlug': typeof ListenSlugEpisodeSlugRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/podcasts/$slug/manage': typeof AuthedPodcastsSlugManageRoute
  '/api/episodes/$id/activity': typeof ApiEpisodesIdActivityRoute
  '/api/episodes/$id/audio': typeof ApiEpisodesIdAudioRoute
  '/api/podcasts/$slug/events': typeof ApiPodcastsSlugEventsRoute
  '/podcasts/$slug_/episodes/$episodeSlug': typeof PodcastsSlugEpisodesEpisodeSlugRoute
  '/_authed/podcasts/$slug_/episodes/$episodeSlug/manage': typeof AuthedPodcastsSlugEpisodesEpisodeSlugManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/tos'
    | '/security'
    | '/settings'
    | '/api/images'
    | '/api/uploads'
    | '/feed/$slug'
    | '/images/$file'
    | '/podcasts/$slug'
    | '/s/$shortSlug'
    | '/settings/security'
    | '/admin/queues/$'
    | '/api/auth/$'
    | '/embed/$slug/$episodeSlug'
    | '/listen/$slug/$episodeSlug'
    | '/admin/'
    | '/settings/'
    | '/podcasts/$slug/manage'
    | '/api/episodes/$id/activity'
    | '/api/episodes/$id/audio'
    | '/api/podcasts/$slug/events'
    | '/podcasts/$slug/episodes/$episodeSlug'
    | '/podcasts/$slug/episodes/$episodeSlug/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/tos'
    | '/security'
    | '/api/images'
    | '/api/uploads'
    | '/feed/$slug'
    | '/images/$file'
    | '/podcasts/$slug'
    | '/s/$shortSlug'
    | '/settings/security'
    | '/admin/queues/$'
    | '/api/auth/$'
    | '/embed/$slug/$episodeSlug'
    | '/listen/$slug/$episodeSlug'
    | '/admin'
    | '/settings'
    | '/podcasts/$slug/manage'
    | '/api/episodes/$id/activity'
    | '/api/episodes/$id/audio'
    | '/api/podcasts/$slug/events'
    | '/podcasts/$slug/episodes/$episodeSlug'
    | '/podcasts/$slug/episodes/$episodeSlug/manage'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/privacy'
    | '/tos'
    | '/_authed/security'
    | '/_authed/settings'
    | '/api/images'
    | '/api/uploads'
    | '/feed/$slug'
    | '/images/$file'
    | '/podcasts/$slug'
    | '/s/$shortSlug'
    | '/_authed/settings/security'
    | '/admin/queues/$'
    | '/api/auth/$'
    | '/embed/$slug/$episodeSlug'
    | '/listen/$slug/$episodeSlug'
    | '/_authed/admin/'
    | '/_authed/settings/'
    | '/_authed/podcasts/$slug/manage'
    | '/api/episodes/$id/activity'
    | '/api/episodes/$id/audio'
    | '/api/podcasts/$slug/events'
    | '/podcasts/$slug_/episodes/$episodeSlug'
    | '/_authed/podcasts/$slug_/episodes/$episodeSlug/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TosRoute: typeof TosRoute
  ApiImagesRoute: typeof ApiImagesRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  FeedSlugRoute: typeof FeedSlugRoute
  ImagesFileRoute: typeof ImagesFileRoute
  PodcastsSlugRoute: typeof PodcastsSlugRoute
  SShortSlugRoute: typeof SShortSlugRoute
  AdminQueuesSplatRoute: typeof AdminQueuesSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EmbedSlugEpisodeSlugRoute: typeof EmbedSlugEpisodeSlugRoute
  ListenSlugEpisodeSlugRoute: typeof ListenSlugEpisodeSlugRoute
  ApiEpisodesIdActivityRoute: typeof ApiEpisodesIdActivityRoute
  ApiEpisodesIdAudioRoute: typeof ApiEpisodesIdAudioRoute
  ApiPodcastsSlugEventsRoute: typeof ApiPodcastsSlugEventsRoute
  PodcastsSlugEpisodesEpisodeSlugRoute: typeof PodcastsSlugEpisodesEpisodeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/security': {
      id: '/_authed/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthedSecurityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/images': {
      id: '/api/images'
      path: '/api/images'
      fullPath: '/api/images'
      preLoaderRoute: typeof ApiImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug': {
      id: '/feed/$slug'
      path: '/feed/$slug'
      fullPath: '/feed/$slug'
      preLoaderRoute: typeof FeedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$file': {
      id: '/images/$file'
      path: '/images/$file'
      fullPath: '/images/$file'
      preLoaderRoute: typeof ImagesFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$slug': {
      id: '/podcasts/$slug'
      path: '/podcasts/$slug'
      fullPath: '/podcasts/$slug'
      preLoaderRoute: typeof PodcastsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shortSlug': {
      id: '/s/$shortSlug'
      path: '/s/$shortSlug'
      fullPath: '/s/$shortSlug'
      preLoaderRoute: typeof SShortSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsSecurityRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/admin/queues/$': {
      id: '/admin/queues/$'
      path: '/admin/queues/$'
      fullPath: '/admin/queues/$'
      preLoaderRoute: typeof AdminQueuesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$slug/$episodeSlug': {
      id: '/embed/$slug/$episodeSlug'
      path: '/embed/$slug/$episodeSlug'
      fullPath: '/embed/$slug/$episodeSlug'
      preLoaderRoute: typeof EmbedSlugEpisodeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/$slug/$episodeSlug': {
      id: '/listen/$slug/$episodeSlug'
      path: '/listen/$slug/$episodeSlug'
      fullPath: '/listen/$slug/$episodeSlug'
      preLoaderRoute: typeof ListenSlugEpisodeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/podcasts/$slug/manage': {
      id: '/_authed/podcasts/$slug/manage'
      path: '/podcasts/$slug/manage'
      fullPath: '/podcasts/$slug/manage'
      preLoaderRoute: typeof AuthedPodcastsSlugManageRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/episodes/$id/activity': {
      id: '/api/episodes/$id/activity'
      path: '/api/episodes/$id/activity'
      fullPath: '/api/episodes/$id/activity'
      preLoaderRoute: typeof ApiEpisodesIdActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/episodes/$id/audio': {
      id: '/api/episodes/$id/audio'
      path: '/api/episodes/$id/audio'
      fullPath: '/api/episodes/$id/audio'
      preLoaderRoute: typeof ApiEpisodesIdAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podcasts/$slug/events': {
      id: '/api/podcasts/$slug/events'
      path: '/api/podcasts/$slug/events'
      fullPath: '/api/podcasts/$slug/events'
      preLoaderRoute: typeof ApiPodcastsSlugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$slug_/episodes/$episodeSlug': {
      id: '/podcasts/$slug_/episodes/$episodeSlug'
      path: '/podcasts/$slug/episodes/$episodeSlug'
      fullPath: '/podcasts/$slug/episodes/$episodeSlug'
      preLoaderRoute: typeof PodcastsSlugEpisodesEpisodeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/podcasts/$slug_/episodes/$episodeSlug/manage': {
      id: '/_authed/podcasts/$slug_/episodes/$episodeSlug/manage'
      path: '/podcasts/$slug/episodes/$episodeSlug/manage'
      fullPath: '/podcasts/$slug/episodes/$episodeSlug/manage'
      preLoaderRoute: typeof AuthedPodcastsSlugEpisodesEpisodeSlugManageRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsSecurityRoute: typeof AuthedSettingsSecurityRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsSecurityRoute: AuthedSettingsSecurityRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedSecurityRoute: typeof AuthedSecurityRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedPodcastsSlugManageRoute: typeof AuthedPodcastsSlugManageRoute
  AuthedPodcastsSlugEpisodesEpisodeSlugManageRoute: typeof AuthedPodcastsSlugEpisodesEpisodeSlugManageRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSecurityRoute: AuthedSecurityRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedPodcastsSlugManageRoute: AuthedPodcastsSlugManageRoute,
  AuthedPodcastsSlugEpisodesEpisodeSlugManageRoute:
    AuthedPodcastsSlugEpisodesEpisodeSlugManageRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TosRoute: TosRoute,
  ApiImagesRoute: ApiImagesRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  FeedSlugRoute: FeedSlugRoute,
  ImagesFileRoute: ImagesFileRoute,
  PodcastsSlugRoute: PodcastsSlugRoute,
  SShortSlugRoute: SShortSlugRoute,
  AdminQueuesSplatRoute: AdminQueuesSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EmbedSlugEpisodeSlugRoute: EmbedSlugEpisodeSlugRoute,
  ListenSlugEpisodeSlugRoute: ListenSlugEpisodeSlugRoute,
  ApiEpisodesIdActivityRoute: ApiEpisodesIdActivityRoute,
  ApiEpisodesIdAudioRoute: ApiEpisodesIdAudioRoute,
  ApiPodcastsSlugEventsRoute: ApiPodcastsSlugEventsRoute,
  PodcastsSlugEpisodesEpisodeSlugRoute: PodcastsSlugEpisodesEpisodeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
